name: Build Rapfi WASM

on:
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure WASM
        run: |
          mkdir -p Rapfi/build/wasm-single

          cd Rapfi/build/wasm-single

          emcmake cmake ../.. \
            -DCMAKE_BUILD_TYPE=Release \
            -DNO_COMMAND_MODULES=ON \
            -DNO_MULTI_THREADING=ON \
            -DUSE_WASM_SIMD=ON \
            -DUSE_WASM_SIMD_RELAXED=OFF

      - name: Build WASM
        run: |
          cd Rapfi/build/wasm-single
          emmake cmake --build . -j2

      - name: Show output
        run: |
          find Rapfi/build/wasm-single -maxdepth 2 -type f | sort

      - name: Upload WASM
        uses: actions/upload-artifact@v4
        with:
          name: rapfi-wasm-single-simd128
          path: |
            Rapfi/build/wasm-single/rapfi-single-simd128.js
            Rapfi/build/wasm-single/rapfi-single-simd128.wasm
            Rapfi/build/wasm-single/rapfi-single-simd128.data